[package]
name = "chs"
version = "0.0.0"
edition = "2021"
authors = ["Thomas Reddy <contact@thomasreddy.com>"]
description = "All things chess."
keywords = []
repository = "https://github.com/Augigogigi/chs"
license = "MIT OR Apache-2.0"
readme = "README.md"

[dependencies]
